config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :tasks
  end
  resources :comments
  resources :teams
  namespace :user do
    post :tasks, to: 'tasks#index'
    resources :tasks, only: [:index, :show]
  end
  resources :reports, only: [:index]

  get 'reports/all_users_tasks'
  get 'reports/tasks_in_projects'
  get 'dashboard/index'
  get 'dashboard/no_access'
  get 'about' => 'dashboard#about'
  get 'user' => 'user#show'
  get 'user_tasks' => 'tasks#user_tasks'
  get 'tz' => 'dashboard#tz'

  root 'dashboard#index'

end

app/models/task.rb
class Task < ApplicationRecord
  paginates_per 20
  include CanCan::Ability
  belongs_to :project
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_many :comments, as: :commentable

  validates :title, length: { minimum: 3, maximum: 100 }
  validates :content, length: { minimum: 3, maximum: 250 }

  enum status: [:open, :in_progress, :done]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  paginates_per 20
  include CanCan::Ability
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :confirmable

  before_save :downcase_email
  validates :first_name, :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum: 5, maximum: 250 }, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_many :tasks
  has_many :projects, through: :tasks
  has_many :comments, dependent: :destroy
  belongs_to :team, optional: true

  def name
    first_name + ' ' + last_name
  end

  def team_name
    if team == nil
      'None'
    else
      team.name
    end
  end

  private

  def downcase_email
    self.email = email.downcase
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :destroy, :update]

  def index
    @tasks = @project.tasks.page(params[:page])
  end

  def new
    @task = @project.tasks.build
  end

  def create
    @task = @project.tasks.build(task_params)
    if @task.save
      redirect_to project_tasks_path(@project)
    else
      render :new
    end
  end

  def edit; end

  def show
    @comments = @task.comments.page(params[:page])
  end

  def update
    if @task.update(task_params)
      redirect_to project_tasks_path(@project)
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @task
    @task.destroy
    redirect_to project_tasks_path(@project)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :status, :content, :start_date, :due_date, :estimation, :project_id, :user_id, :image)
  end
end

app/controllers/user/tasks_controller.rb
class User::TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    if request.post?
      @tasks = current_user.tasks.where(user_tasks_params).page(params[:page])
    else
      @tasks = current_user.tasks.page(params[:page])
    end
  end

  private

  def user_tasks_params
    params.require('/user/tasks').permit(:title, :project_id)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = current_user
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/tasks/_tasks.html.erb
<h3>
  <% tasks.each do |t| %>
    <li><h6>Id task: <strong><%= t.id %></strong></h6></li>
    <li><h6>Task title: <strong><%= t.title %></strong></h6></li>
    <li><h6>Status: <strong><%= t.status %></strong></h6></li>
    </h3>
    <div class="task_show">
      <h6><%= link_to 'More details', project_task_path(t.project_id, t.id) %> </h6>
    </div>
    <p>---------</p>
  <% end %>
  <p><%= paginate tasks, remote: true %></p>

app/views/user/tasks/index.html.erb
<%= form_for user_tasks_path, remote: true do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.collection_select :project_id, Project.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit 'Search', remote: true %>
  </div>
<% end %>

<div class="user_tasks">
  <%= render 'user/tasks/tasks', tasks: @tasks %>
</div>

app/views/user/tasks/index.js.erb
$('.user_tasks').html("<%= j render 'user/tasks/tasks', tasks: @tasks %>");