config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :tasks
  end
  resources :comments
  resources :teams
  namespace :user do
    post :tasks, to: 'tasks#index'
    resources :tasks, only: [:index, :show]
  end
  resources :reports, only: [:index]

  get 'reports/all_users_tasks'
  get 'reports/tasks_in_projects'
  get 'dashboard/index'
  get 'dashboard/no_access'
  get 'about' => 'dashboard#about'
  get 'user' => 'user#show'
  get 'user_tasks' => 'tasks#user_tasks'
  get 'tz' => 'dashboard#tz'

  root 'dashboard#index'

end

app/models/task.rb
class Task < ApplicationRecord
  paginates_per 20
  include CanCan::Ability
  belongs_to :project
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_many :comments, as: :commentable

  validates :title, length: { minimum: 3, maximum: 100 }
  validates :content, length: { minimum: 3, maximum: 250 }

  enum status: [:open, :in_progress, :done]

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :destroy, :update]

  def index
    @tasks = @project.tasks.page(params[:page])
  end

  def new
    @task = @project.tasks.build
  end

  def create
    @task = @project.tasks.build(task_params)
    if @task.save
      redirect_to project_tasks_path(@project)
    else
      render :new
    end
  end

  def edit; end

  def show
    @comments = @task.comments.page(params[:page])
  end

  def update
    if @task.update(task_params)
      redirect_to project_tasks_path(@project)
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @task
    @task.destroy
    redirect_to project_tasks_path(@project)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :status, :content, :start_date, :due_date, :estimation, :project_id, :user_id, :image)
  end
end

app/controllers/user/tasks_controller.rb
class User::TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    if request.post?
      @tasks = current_user.tasks.where(user_tasks_params).page(params[:page])
    else
      @tasks = current_user.tasks.page(params[:page])
    end
  end

  private

  def user_tasks_params
    params.require('/user/tasks').permit(:title, :project_id)
  end

end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.radio_button :status, :open %>
    <%= f.label :status, "Open" %>
    <%= f.radio_button :status, :in_progress %>
    <%= f.label :status, "In progress" %>
    <%= f.radio_button :status, :done %>
    <%= f.label :status, "Done" %>
  </div>

  <div class="field">
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>

  <div class="field">
    <%= f.label :estimation %><br>
    <%= f.number_field :estimation %>
  </div>

  <div class="field">
    <br>
    <%= f.hidden_field :project_id, value: @project.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @task.new_record? ? 'Create' : 'Edit'}" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="task">
  <li><h4>Id task: <strong><%= @task.id %></strong></h4></li>
  <li><h4>Task title: <strong><%= @task.title %></strong></h4></li>
  <li><h4>Task content: <strong><%= @task.content %></strong></h4></li>
  <li><h4>Task status: <strong><%= @task.status %></strong></h4></li>
  <li><h4>Start date: <strong><%= @task.start_date %></strong></h4></li>
  <li><h4>Period of execution: <strong><%= @task.due_date %></strong></h4></li>
  <li><h4>Estimation: <strong><%= @task.estimation %> hours</strong></h4></li>
  <% if @task.image.attached? %>
    <%= image_tag @task.image.representation(resize: "100x100") %>
  <% else %>
    <strong>No image</strong>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form' %>


<%= link_to 'Back', project_task_path(@project) %>

app/views/tasks/index.html.erb
<h3>
  <% @tasks.each do |t| %>
    <li><h6>Id task: <strong><%= t.id %></strong></h6></li>
    <li><h6>Task title: <strong><%= t.title %></strong></h6></li>
    <li><h6>Status: <strong><%= t.status %></strong></h6></li>
    </h3>
    <h6><%= link_to 'More details', project_task_path(@project, t.id) %> </h6>
    <p>---------</p>
  <% end %>
  <h5><%= link_to 'New task', new_project_task_path(@project) %></h5>
  <h5><%= link_to 'Back', project_path(@project) %></h5>
  <p><%= paginate @tasks %></p>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>


<%= link_to 'Back', project_path(@project) %>

app/views/tasks/show.html.erb
<%= render 'task' %>
<% if can? :edit, @task %>
  <h5><%= link_to 'Edit', edit_project_task_path(@task.project_id) %></h5>
<% end %>
<% if can? :delete, @task %>
  <h5><%= link_to 'Delete', [@project, @task], method: :delete, data: { confirm: "You sure?" }, title: "Delete" %></h5>
<% end %>
<p>---------</p>
<h5><%= link_to 'New task', new_project_task_path(@project) %></h5>
<h5><%= link_to 'Back', project_tasks_path(@project) %></h5>
<p>---------</p>
<h4>Comments:</h4>
<ul>
  <%= render @comments %>
  <p><%= paginate @comments %></p>
</ul>
<%= render "comments/comment_form", commentable_type: "Task", commentable_id: @task.id %>

app/views/tasks/show.js.erb
$('.show_task').html("<%= j render 'task', task: @task %>");