config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :tasks
  end
  resources :comments
  resources :teams
  namespace :user do
    post :tasks, to: 'tasks#index'
    resources :tasks, only: [:index, :show]
  end
  resources :reports, only: [:index]

  get 'reports/all_users_tasks'
  get 'reports/tasks_in_projects'
  get 'dashboard/index'
  get 'dashboard/no_access'
  get 'about' => 'dashboard#about'
  get 'user' => 'user#show'
  get 'user_tasks' => 'tasks#user_tasks'
  get 'tz' => 'dashboard#tz'

  root 'dashboard#index'

end

app/models/project.rb
class Project < ApplicationRecord
  paginates_per 20
  include CanCan::Ability
  has_many :teams
  has_many :tasks, dependent: :destroy
  has_many :users, through: :tasks
  has_many :comments, as: :commentable

  validates :start_date, :end_date, presence: true
  validates :name, length: { minimum: 3, maximum: 100 }, uniqueness: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :destroy, :update]

  def index
    @projects = current_user.projects
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def edit
    authorize! :edit, @project
  end

  def show
    @comments = @project.comments.page(params[:page])
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @project
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :summary, :start_date, :end_date)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>

  <div class="field">
    <br>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <!--  summary: string, start_date: datetime, end_date: datetime-->

  <div class="actions">
    <%= f.submit "#{ @project.new_record? ? 'Create' : 'Edit'}" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<%= render 'form' %>


<%= link_to 'Back', project_path(@project) %>

app/views/projects/index.html.erb
<h3>All your projects:</h3>
<h4>
  <% @projects.each do |t| %>
    <li><%= link_to t.name, project_path(t) %></li>
  <% end %></h4>
--------------------------------------------------------------
<h5><%= link_to 'Create new project', new_project_path %></h5>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>


<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h4>Name of project: <strong><%= @project.name %></strong></h4>
<h4>ID: <strong><%= @project.id %></strong></h4>
<h4>Summary: <strong><%= @project.summary %></strong></h4>
<h4>Start date: <strong><%= @project.start_date %></strong></h4>
<h4>End date: <strong><%= @project.end_date %></strong></h4>
<% if can? :edit, @project %>
  <h5><%= link_to 'Edit', edit_project_path(@project.id) %></h5>
<% end %>
<% if can? :delete, @project %>
  <h5><%= link_to 'Delete', @project, method: :delete, data: { confirm: "You sure?" }, title: "Delete #{@project.name}" %></h5>
<% end %>
-----------------------------------------------------------------------------
<h4>Number of tasks: <strong><%= @project.tasks.length %></strong></h4>
<h5><%= link_to 'Task management', project_tasks_path(@project) %></h5>
<h5><%= link_to 'New task', new_project_task_path(@project) %></h5>
<h5><%= link_to 'Back', projects_path %></h5>
-----------------------------------------------------------------------------
<h3>Comments</h3>
<ul>
  <%= render @comments %>
  <p><%= paginate @comments %></p>
</ul>
<%= render "comments/comment_form", commentable_type: "Project", commentable_id: @project.id %>