config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :tasks
  end
  resources :comments
  resources :teams
  namespace :user do
    post :tasks, to: 'tasks#index'
    resources :tasks, only: [:index, :show]
  end
  resources :reports, only: [:index]

  get 'reports/all_users_tasks'
  get 'reports/tasks_in_projects'
  get 'dashboard/index'
  get 'dashboard/no_access'
  get 'about' => 'dashboard#about'
  get 'user' => 'user#show'
  get 'user_tasks' => 'tasks#user_tasks'
  get 'tz' => 'dashboard#tz'

  root 'dashboard#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_parametrs
  before_action :check_permissions

  def index
    authorize! :read, @projects
  end

  def all_users_tasks
    authorize! :read, @users
  end

  def tasks_in_projects
    authorize! :read, @projects
  end

  private

  def set_parametrs
    @projects = Project.all.page(params[:page])
    @users = User.all.page(params[:page])
  end

  def check_permissions
    redirect_to dashboard_no_access_path unless current_user.admin?
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/all_users_tasks.html.erb
<h3>All users tasks:</h3>
<h4>
  <div class="table">
    <table border="1">
      <tr>
        <th>Name:</th>
        <th>ID:</th>
        <th>Tasks:</th>
        <th>Open:</th>
        <th>In progress:</th>
        <th>Done:</th>
      </tr>
      <% @users.each do |t| %>
        <tr>
          <td><%= t.first_name %></td>
          <td><%= t.id %></td>
          <td><%= t.tasks.size %></td>
          <td><%= t.tasks.open.count %></td>
          <td><%= t.tasks.in_progress.count %></td>
          <td><%= t.tasks.done.count %></td>
        </tr>
      <% end %>
    </table>
  </div>
</h4>
<%= link_to "Back", reports_path %>
<p><%= paginate @users %></p>

app/views/reports/index.html.erb
<h3><%= link_to "All projects tasks", reports_tasks_in_projects_path %></h3>
<h3><%= link_to "All users tasks", reports_all_users_tasks_path %></h3>

app/views/reports/tasks_in_projects.html.erb
<h3>All projects tasks:</h3>  <%# @projects.each do |t| %>
<!--    <table>-->
<!--      <tr>-->
<!--        <td> Name: "<%#= t.name %>" Tasks: "<%#= t.tasks.size %>"</td>-->
<!--      </tr>-->
<!--      <tr>-->
<!--        <td>Open: <%#= t.tasks.open.count %></td>-->
<!--      </tr>-->
<!--      <tr>-->
<!--        <td>In progress: <%#= t.tasks.in_progress.count %></td>-->
<!--      </tr>-->
<!--      <tr>-->
<!--        <td>Done: <%#= t.tasks.done.count %></td>-->
<!--      </tr>-->
<!--    </table>-->
<!--    <p>-----------------------------</p>-->
<!--  <%# end %></h4>-->
<h4>
  <div class="table">
    <table border="1">
      <tr>
        <th>Name:</th>
        <th>Tasks:</th>
        <th>Open:</th>
        <th>In progress:</th>
        <th>Done:</th>
      </tr>
      <% @projects.each do |t| %>
        <tr>
          <td><%= t.name %></td>
          <td><%= t.tasks.size %></td>
          <td><%= t.tasks.open.count %></td>
          <td><%= t.tasks.in_progress.count %></td>
          <td><%= t.tasks.done.count %></td>
        </tr>
      <% end %>
    </table>
  </div>
</h4>
<%= link_to "Back", reports_path %>
<p><%= paginate @projects %></p>